### ISSUE TITLE
Highlight loop names after CYCLE or EXIT

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#18]
If a DO loop is named and we CYCLE or EXIT the loop, it would be good to have the name highlighted.  For example, in the code below, "CHECK_INTERNAL_WALL_LOOP" could be highlighted after CYCLE.

![screen shot 2016-06-30 at 11 50 26 am](https://cloud.githubusercontent.com/assets/4418497/16494915/35120ba0-3eb9-11e6-9ed1-4cf8b1a797ce.png)

**Comment by 315234** [comment]
Fixed in commit 041a87e, I will wait a while before doing a release though.

**Comment by rmcdermo** [comment]
OK, I was able to test the commit.  Loop names look good.  With this commit though, !$OMP directives look a bit strange.  Did you mean for these to be highlighted?  I am used to them remaining as comments.

![screen shot 2016-07-01 at 8 56 48 am](https://cloud.githubusercontent.com/assets/4418497/16522200/32ffc3d2-3f6a-11e6-8f17-8c9ab7c8c573.png)

**Comment by 315234** [comment]
Thanks for testing. The OMP directives have been highlighted for a while, the implementation is incomplete but it shouldn't cause problems. I think they should be captured because they are not really comments, they are code hiding in comments. If you wanted them to look like comments anyway I think the appropriate place to implement that is in the color scheme itself, rather than in the syntax file.

**Comment by rmcdermo** [comment]
Sounds good.  Thanks.
