### ISSUE TITLE
END SUBROUTINE not highlighted in latest commit

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#19]
Hi.  Just fetched latest commit and the END SUBROUTINE has been affected.

![screen shot 2016-07-01 at 2 07 10 pm](https://cloud.githubusercontent.com/assets/4418497/16530318/908ae6c8-3f95-11e6-911c-3ccf5690e328.png)

**Comment by 315234** [comment]
Case sensitivity problem, fixed in b10b11e758e621681144067c51a19d1ee805ad6e.

**Comment by rmcdermo** [comment]
Got it.  Thanks!  I also figured out a simple way to deal with OMP in my
fork.

**Comment by rmcdermo** [comment]
Maybe more case sensitivity, but first image is latest commit where REAL, SIGN, and fortran literals are not highlighted.  Second image is from v1.0.16 where everything was fine.

![screen shot 2016-07-01 at 2 33 29 pm](https://cloud.githubusercontent.com/assets/4418497/16531144/29954ef0-3f99-11e6-98ca-1873816330fa.png)

![screen shot 2016-07-01 at 2 34 17 pm](https://cloud.githubusercontent.com/assets/4418497/16531148/2dd26d2c-3f99-11e6-932b-d56a0c41455e.png)

**Comment by rmcdermo** [comment]
I guess the literals were fine... 1._EB.  Not sure why I thought they were not.

**Comment by 315234** [comment]
Improved type names is what I'm working on at the moment. It is tricky because when you look at `REAL(X)`, it can be either the start of a type declaration for a `REAL` with size X, or a function call converting X to a `REAL`. The only way to tell the difference is from the context i.e. is it in the declaration section or the executable section. Or you can look to see if the line ends with a variable name, but that gets tricky when you have possibilities like

``` fortran
real(x), allocatable, private, & ! random comment
            intent(in), dimension(*) :: varname
```
