### ISSUE TITLE
Rulers everywhere

### ISSUE THREAD

**Issue by fredaas** [Nevensky/SublimeFortran#34]
Just installed the package from withing ST3, and this how my screen looks like out of the box:

![rulers](https://user-images.githubusercontent.com/10281443/35383096-9066593a-01c1-11e8-96d8-779bff78ce55.png)

The ruler to the far right is from my global ST3 settings, but what is the purpose of those other four? Is this intended behavior of the package? Why would I ever want four rulers in this arrangement?

If this is not a bug, I would strongly suggest to remove the default ruler setup as it is just annoying and looks ugly. That I actively have to create a settings file to explicitly remove the rulers just degrades the whole experience for me.

**Comment by 315234** [comment]
The rulers are there to help distinguish special columns in legacy fortran. They are showing up for you because you have named your file `.f`. The correct file extension for modern fortran is `.f90`. Alternatively you could just change the selected syntax to modern fortran or override the language specific settings file in your user folder.
