### ISSUE TITLE
how about adding an auto-complete function?

### ISSUE THREAD

**Issue by sequencer** [Nevensky/SublimeFortran#5]

**Comment by 315234** [comment]
Since Fortran is very limited I'm not sure what this could provide beyond completion for the built in subroutines. Doing OO style autocomplete would have limited value and require a parser, which isn't available. I plan about adding some snippets when I get a chance.

What did you have in mind? Personally I'm not a big fan of autocomplete anyway. It tends to get in my way more than it helps. If you felt like working on it though I'd be happy to accept pull requests.

**Comment by 315234** [comment]
I have added some snippets in the latest version.

**Comment by sequencer** [comment]
oops! Sorry, I forgot to reply.
because I'm a beginner to Fortran.
So I might need auto-complete to learn.
Thank you!
